import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Phone from "@/components/Phone";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "대양잠수개발",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f0f0f0]`}>
        <div className="min-h-screen flex flex-col">
          <Header />

          {/* 콘텐츠 영역이 남은 공간을 차지 */}
          <main className="flex-1">{children}</main>
          <Phone />
          <Footer />
        </div>
      </body>
    </html>
  );
}
